/* eslint-disable @typescript-eslint/no-explicit-any */
declare global {
  interface Window {
    _paq?: any[];
  }
}

/**
 * Tracks a custom event in Matomo.
 * @param category e.g. "Checkout", "AI Agent", "KDS"
 * @param action e.g. "Place Order", "Submit Prompt", "Cook Completed"
 * @param name Optional label, e.g. "Order #1234", "Category 'warm-coffee'"
 * @param value Optional numeric value, e.g. 250 (amount or time)
 */
export function trackEvent(category: string, action: string, name?: string, value?: number) {
  if (typeof window !== 'undefined' && window._paq) {
    const payload: any[] = ['trackEvent', category, action];
    if (name !== undefined) payload.push(name);
    if (value !== undefined) payload.push(value);
    window._paq.push(payload);
  }
}

/**
 * Tracks a Goal completion in Matomo.
 * @param goalId Numeric Goal ID configured in your Matomo console
 * @param revenue Optional revenue generated by this goal
 */
export function trackGoal(goalId: number, revenue?: number) {
  if (typeof window !== 'undefined' && window._paq) {
    const payload: any[] = ['trackGoal', goalId];
    if (revenue !== undefined) payload.push(revenue);
    window._paq.push(payload);
  }
}

/**
 * Tracks employee or customer user ID for session mapping.
 * @param userId Unique username or ID
 */
export function setUserId(userId: string) {
  if (typeof window !== 'undefined' && window._paq) {
    window._paq.push(['setUserId', userId]);
  }
}

/**
 * Resets user ID mapping on logout.
 */
export function resetUserId() {
  if (typeof window !== 'undefined' && window._paq) {
    window._paq.push(['resetUserId']);
  }
}
